### ISSUE TITLE
Show view programmatically 

### ISSUE THREAD

**Issue by machukas** [sochalewski/PSPageControl#2]
Hi, now showView is marked as _fileprivate_, so we can't set a concrete view programmatically.

Are you planning to modify this?

Thanks a lot!

**Comment by sochalewski** [comment]
Hi @machukas,

It's done in 0.2.1 through `showView(withIndex:)` function. Hope that it works fine :)

**Comment by machukas** [comment]
Thanks! it does indeed ;)
